version: "3"

services:
  app:
    container_name: material_app
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
      - ./tests:/app/tests
      - ./material:/app/material
      - ./docker:/app/docker
    env_file: "./docker/environments"
    depends_on:
      - db

  db:
    container_name: material_db
    image: postgres:12
    env_file: "./docker/environments"
    ports:
      - "5432:5432"
