# Generated by Django 4.2.5 on 2023-12-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0020_auto_20200713_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries Test label value (length). Requires more text.'},
        ),
    ]
